### ISSUE TITLE
New problem

### ISSUE THREAD

**Issue by obtim** [mg07926/NBA_webscrapper#2]
Changed 
team_profile = soup.find_all('div', class_= 'flex text-sm')
to:
team_profile = soup.find_all('div', class_= 'TeamFigure_tfLinks__i6-eh')
Got
Saving:  Rodney McGruder
Saving:  Svi Mykhailiuk
Saving:  Josh Jackson
Saving:  Blake Griffin
Saving:  Mason Plumlee
Saving:  Derrick Rose
Saving:  Isaiah Stewart
Saving:  Saben Lee
Saving:  Saddiq Bey
Saving:  Sekou Doumbouya
Saving:  Delon Wright
Saving:  Deividas Sirvydis
Saving:  Detroit Pistons
Saving:  Jalen Lecque
Saving:  T.J. Warren
Saving:  Cassius Stanley
Saving:  Aaron Holiday
Traceback (most recent call last):
  File "Scrapper2.py", line 98, in <module>
    FirstName = Player_name[0].text.strip()
IndexError: list index out of range

I use Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM D64)] on win32

**Comment by mg07926** [comment]
This web scraper is built based on dynamic links gathered from the base link " baseurl = 'https://www.nba.com/teams' ". As mentioned in the README, NBA.com will reroute a player's original link to another page with almost similar content but since the page is built differently the code won't work. Wait till NBA fixes the broken link and retry the code. As of right now, Monday, December 28, 2020, 19:12 CST the code works. Any time the error:
File "Scrapper2.py", line 98, in
FirstName = Player_name[0].text.strip()
IndexError: list index out of range

appears it means that the NBA.com's link scrapped from their website is broken for the specific player and they have rerouted to another link where the page is built differently as to what the code is looking for.

**Comment by obtim** [comment]
Thanks! Work's fine now
